packages:
  - packages/*
catalog:
  "@changesets/cli": ^2.29.8
  "@commitlint/cli": ^20.4.0
  "@commitlint/config-conventional": ^20.4.0
  "@commitlint/types": ^20.4.0
  "@eslint/js": ^9.39.2
  "@types/node": ^25.1.0
  commitizen: ^4.3.1
  cz-conventional-changelog: ^3.3.0
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.5
  eslint-plugin-react: ^7.37.5
  globals: ^17.3.0
  husky: ^9.1.7
  jiti: ^2.6.1
  lint-staged: ^16.2.7
  prettier: 3.8.1
  typescript-eslint: ^8.54.0
