packages:
  - packages/*
catalog:
  "@eslint/js": ^9.39.2
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.5
  eslint-plugin-react: ^7.37.5
  globals: ^17.3.0
  jiti: ^2.6.1
  prettier: 3.8.1
  typescript-eslint: ^8.54.0
