packages:
  - packages/*
catalog:
  "@changesets/cli": ^2.29.8
  "@commitlint/cli": ^20.4.0
  "@commitlint/config-conventional": ^20.4.0
  "@commitlint/types": ^20.4.0
  "@docusaurus/core": 3.9.2
  "@docusaurus/module-type-aliases": 3.9.2
  "@docusaurus/preset-classic": 3.9.2
  "@docusaurus/theme-mermaid": ^3.9.2
  "@docusaurus/tsconfig": 3.9.2
  "@docusaurus/types": 3.9.2
  "@easyops-cn/docusaurus-search-local": ^0.52.3
  "@eslint/js": ^9.39.2
  "@mdx-js/react": ^3.0.0
  "@types/node": ^25.1.0
  "@types/react": ^19.2.10
  "@types/react-dom": ^19.2.3
  clsx: ^2.0.0
  commitizen: ^4.3.1
  cz-conventional-changelog: ^3.3.0
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-plugin-import: ^2.32.0
  eslint-plugin-prettier: ^5.5.5
  eslint-plugin-react: ^7.37.5
  globals: ^17.3.0
  husky: ^9.1.7
  jiti: ^2.6.1
  lint-staged: ^16.2.7
  prettier: 3.8.1
  prism-react-renderer: ^2.3.0
  raw-loader: ^4.0.2
  react: ^19.0.0
  react-dom: ^19.0.0
  typescript: ~5.6.2
  typescript-eslint: ^8.54.0
