import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebarsDocs: SidebarsConfig = {
  sidebarsDocs: [{ type: "autogenerated", dirName: "." }],
};

export default sidebarsDocs;
