import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// 这在 Node.js 中运行 - 不要在这里使用客户端代码（浏览器 API、JSX...）

/**
 * 创建侧边栏使你能够：
 - 创建有序的文档组
 - 为该组的每个文档渲染侧边栏
 - 提供上一页/下一页导航

 侧边栏可以从文件系统生成，或在此处显式定义。

 创建任意数量的侧边栏。
 */
const sidebarsExamples: SidebarsConfig = {
  // 默认情况下，Docusaurus 从 docs 文件夹结构生成侧边栏
  sidebarsExamples: [{ type: "autogenerated", dirName: "." }],

  // 但你可以手动创建侧边栏
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebarsExamples;
